#!/usr/bin/env python3
"""Minimal two-module swerve controller for Phase 3.

The node deliberately publishes directly to the two ros2_control group
controller command topics.  It does not estimate odometry or use cmd_vel
feedback, so all motion remains generated by Gazebo physics.
"""

import math
from typing import Dict, Optional

import rclpy
from geometry_msgs.msg import Twist
from rclpy.node import Node
from sensor_msgs.msg import JointState
from std_msgs.msg import Float64MultiArray


def normalize_angle(angle: float) -> float:
    """Return angle in [-pi, pi]."""
    return (angle + math.pi) % (2.0 * math.pi) - math.pi


def shortest_delta(target: float, current: float) -> float:
    return normalize_angle(target - current)


class SwerveController(Node):
    def __init__(self) -> None:
        super().__init__('swerve_controller')

        self.declare_parameter('wheel_radius', 0.0675)
        self.declare_parameter('max_wheel_velocity', 30.0)
        self.declare_parameter('max_wheel_acceleration', 10.0)
        self.declare_parameter('max_steering_rate', 2.0)
        self.declare_parameter('command_timeout', 0.5)
        self.declare_parameter('control_rate', 50.0)
        self.declare_parameter('speed_deadband', 0.01)
        self.declare_parameter('modules.front.x', 0.300042)
        self.declare_parameter('modules.front.y', 0.049988)
        self.declare_parameter('modules.rear.x', -0.300042)
        self.declare_parameter('modules.rear.y', 0.050013)

        self.wheel_radius = float(self.get_parameter('wheel_radius').value)
        self.max_wheel_velocity = float(self.get_parameter('max_wheel_velocity').value)
        self.max_wheel_acceleration = float(
            self.get_parameter('max_wheel_acceleration').value)
        self.max_steering_rate = float(self.get_parameter('max_steering_rate').value)
        self.command_timeout = float(self.get_parameter('command_timeout').value)
        self.speed_deadband = float(self.get_parameter('speed_deadband').value)
        control_rate = float(self.get_parameter('control_rate').value)

        self.modules = ('front', 'rear')
        self.module_xy = {
            'front': (
                float(self.get_parameter('modules.front.x').value),
                float(self.get_parameter('modules.front.y').value),
            ),
            'rear': (
                float(self.get_parameter('modules.rear.x').value),
                float(self.get_parameter('modules.rear.y').value),
            ),
        }
        self.steer_joints = {
            'front': 'steer_front_joint',
            'rear': 'steer_rear_joint',
        }
        self.drive_joints = {
            'front': 'wheel_front_drive_joint',
            'rear': 'wheel_rear_drive_joint',
        }

        self.steering_state: Dict[str, float] = {'front': 0.0, 'rear': 0.0}
        self.steering_command: Dict[str, float] = {'front': 0.0, 'rear': 0.0}
        self.wheel_command = {'front': 0.0, 'rear': 0.0}
        self.last_cmd_time: Optional[float] = None
        self.last_update_time = self.get_clock().now()
        self.last_timeout_warning = self.get_clock().now()

        self.steer_pub = self.create_publisher(
            Float64MultiArray, '/steering_controller/commands', 10)
        self.drive_pub = self.create_publisher(
            Float64MultiArray, '/drive_controller/commands', 10)
        self.create_subscription(Twist, '/cmd_vel', self.cmd_vel_callback, 10)
        self.create_subscription(JointState, '/joint_states', self.joint_state_callback, 10)
        self.timer = self.create_timer(1.0 / control_rate, self.update)

        self.get_logger().info(
            f'Swerve controller ready: radius={self.wheel_radius:.4f} m, '
            f'modules={self.module_xy}')

    def joint_state_callback(self, msg: JointState) -> None:
        values = dict(zip(msg.name, msg.position))
        for module in self.modules:
            joint = self.steer_joints[module]
            if joint in values and math.isfinite(values[joint]):
                self.steering_state[module] = normalize_angle(values[joint])

    def cmd_vel_callback(self, msg: Twist) -> None:
        self.last_cmd_time = self.get_clock().now().nanoseconds * 1e-9
        vx, vy, wz = msg.linear.x, msg.linear.y, msg.angular.z
        targets = {}

        for module in self.modules:
            x, y = self.module_xy[module]
            module_vx = vx - wz * y
            module_vy = vy + wz * x
            linear_speed = math.hypot(module_vx, module_vy)

            # At zero speed atan2 is undefined for control purposes. Keep the
            # latest physical/commanded steering angle and command zero drive.
            if linear_speed <= self.speed_deadband:
                targets[module] = (self.steering_command[module], 0.0)
                continue

            angle = normalize_angle(math.atan2(module_vy, module_vx))
            speed = linear_speed / self.wheel_radius

            current = self.steering_state[module]
            if abs(shortest_delta(angle, current)) > math.pi / 2.0:
                angle = normalize_angle(angle + math.pi)
                speed = -speed
            targets[module] = (angle, speed)

        self.targets = targets

    def update(self) -> None:
        now = self.get_clock().now()
        dt = max(1e-4, (now - self.last_update_time).nanoseconds * 1e-9)
        self.last_update_time = now

        timed_out = (
            self.last_cmd_time is None or
            (now.nanoseconds * 1e-9 - self.last_cmd_time) > self.command_timeout)
        if timed_out:
            # Safe stop: hold steering, ramp drive speed down to zero.
            targets = {
                module: (self.steering_command[module], 0.0)
                for module in self.modules
            }
            if self.last_cmd_time is not None:
                elapsed = (now - self.last_timeout_warning).nanoseconds * 1e-9
                if elapsed > 2.0:
                    self.get_logger().warn('cmd_vel timeout: stopping drive wheels')
                    self.last_timeout_warning = now
        else:
            targets = getattr(self, 'targets', {
                module: (self.steering_command[module], 0.0)
                for module in self.modules
            })

        for module in self.modules:
            target_angle, target_speed = targets[module]
            max_angle_step = self.max_steering_rate * dt
            angle_step = shortest_delta(target_angle, self.steering_command[module])
            angle_step = max(-max_angle_step, min(max_angle_step, angle_step))
            self.steering_command[module] = normalize_angle(
                self.steering_command[module] + angle_step)

            target_speed = max(
                -self.max_wheel_velocity,
                min(self.max_wheel_velocity, target_speed))
            max_speed_step = self.max_wheel_acceleration * dt
            speed_step = target_speed - self.wheel_command[module]
            speed_step = max(-max_speed_step, min(max_speed_step, speed_step))
            self.wheel_command[module] += speed_step

        self.steer_pub.publish(Float64MultiArray(data=[
            self.steering_command['front'], self.steering_command['rear']]))
        self.drive_pub.publish(Float64MultiArray(data=[
            self.wheel_command['front'], self.wheel_command['rear']]))


def main(args=None) -> None:
    rclpy.init(args=args)
    node = SwerveController()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.steer_pub.publish(Float64MultiArray(data=[
            node.steering_command['front'], node.steering_command['rear']]))
        node.drive_pub.publish(Float64MultiArray(data=[0.0, 0.0]))
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
