swerve_controller:
  ros__parameters:
    wheel_radius: 0.0675
    max_wheel_velocity: 30.0
    max_wheel_acceleration: 10.0
    max_steering_rate: 2.0
    command_timeout: 0.5
    control_rate: 50.0
    speed_deadband: 0.01

    modules.front.x: 0.300042
    modules.front.y: 0.0
    modules.rear.x: -0.300042
    modules.rear.y: 0.0
