from django.urls import path
from . import views, warehouse_views, scheduler_views, navigation_views, local_control_views

urlpatterns = [
    path('conveyors', views.conveyors),
    path('conveyors/<str:conveyor_id>/command', views.conveyor_command),
    path('conveyors/<str:conveyor_id>/handshake', views.conveyor_handshake),
    path('scheduler/overview', scheduler_views.scheduler_overview),
    path('scheduler/workpoints', scheduler_views.workpoints),
    path('scheduler/robots', scheduler_views.scheduler_robots),
    path('orders', scheduler_views.orders),
    path('orders/import', scheduler_views.order_import),
    path('shelf-inventory/<str:rack_id>', scheduler_views.shelf_inventory),
    path('inventory-items/<int:item_id>/dispatch', scheduler_views.inventory_item_dispatch),
    path('orders/<int:order_id>', scheduler_views.order_detail),
    path('orders/<int:order_id>/cancel', scheduler_views.order_cancel),
    path('schedules', scheduler_views.schedules),
    path('schedules/preview', scheduler_views.schedule_preview),
    path('schedules/create', scheduler_views.schedule_create),
    path('schedules/<int:schedule_id>', scheduler_views.schedule_detail),
    path('schedules/<int:schedule_id>/cancel', scheduler_views.schedule_cancel),
    # Overview's retained inbound/outbound modal still uses the published
    # shelf catalog. Warehouse administration/editor endpoints are not part of
    # this product surface.
    path('shelves', warehouse_views.shelves),
    path('auth/register', views.auth_register),
    path('auth/login', views.auth_login),
    path('auth/logout', views.auth_logout),
    path('auth/me', views.auth_me),
    path('health', views.health),
    path('health/', views.health),
    path('system/status', views.system_status),
    path('system/status/', views.system_status),
    path('layout', views.layout_get),
    path('map/sync-status', views.map_sync_status_view),
    path('events', views.events),
    path('navigation/tags', navigation_views.tags),
    path('robots/<str:robot_id>/navigation-tags', navigation_views.robot_tags),
    path('robots/<str:robot_id>/map-registration', navigation_views.register_robot_map),
    path('navigation/tag-graph', navigation_views.tag_graph),
    path('navigation/missions/current', navigation_views.current),
    path('navigation/missions', navigation_views.missions),
    path('navigation/missions/start', navigation_views.start),
    path('navigation/missions/<int:mission_id>/<str:action>', navigation_views.mission_action),
    path('navigation/missions/<int:mission_id>/events', navigation_views.mission_events),
    path('robots/<str:robot_id>/emergency-stop', navigation_views.emergency_stop),
    path('robots/<str:robot_id>/clear-emergency-stop', navigation_views.clear_emergency_stop),
    path('robots/<str:robot_id>/local/maps', local_control_views.local_maps),
    path('robots/<str:robot_id>/local/runtime-mode', local_control_views.local_runtime_mode),
    path('robots/<str:robot_id>/local/mapping/<str:action>', local_control_views.mapping_command),
    path('robots/<str:robot_id>/local/maps/save', local_control_views.save_robot_map),
    path('robots/<str:robot_id>/local/maps/load', local_control_views.load_robot_map),
    path('robots/<str:robot_id>/local/maps/resume-session', local_control_views.resume_robot_slam_session),
    path('robots/<str:robot_id>/local/initial-pose', local_control_views.initialize_robot_pose),
    path('robots/<str:robot_id>/local/vda5050', local_control_views.vda5050_configuration),
    path('robots/<str:robot_id>/local/vda5050/test', local_control_views.vda5050_test_connection),
]
