#!/usr/bin/env python3
"""Create lightweight OBJ visual meshes from the source binary STL files.

The source CAD files remain untouched.  This converter uses deterministic
vertex clustering, which is a good fit for Gazebo visual geometry: it keeps
the measured coordinate frame and silhouette while removing the enormous
CAD tessellation that is unnecessary for rendering.  The generated OBJ
vertices are written in metres, so the URDF uses an identity scale.
"""

from __future__ import annotations

import argparse
import struct
from pathlib import Path

import numpy as np


STL_DTYPE = np.dtype(
    [
        ("normal", "<f4", (3,)),
        ("vertices", "<f4", (3, 3)),
        ("attribute", "<u2"),
    ]
)


def read_binary_stl(path: Path) -> np.ndarray:
    data = path.read_bytes()
    if len(data) < 84:
        raise ValueError(f"{path} is not a complete binary STL")
    triangle_count = struct.unpack_from("<I", data, 80)[0]
    expected_size = 84 + triangle_count * 50
    if expected_size != len(data):
        raise ValueError(
            f"{path} has an invalid binary STL size: expected {expected_size}, "
            f"got {len(data)}"
        )
    triangles = np.frombuffer(data, dtype=STL_DTYPE, offset=84, count=triangle_count)
    vertices = np.asarray(triangles["vertices"], dtype=np.float64)
    if not np.isfinite(vertices).all():
        raise ValueError(f"{path} contains non-finite vertex coordinates")
    return vertices


def triangle_area(vertices: np.ndarray) -> float:
    edges_a = vertices[:, 1] - vertices[:, 0]
    edges_b = vertices[:, 2] - vertices[:, 0]
    return float(0.5 * np.linalg.norm(np.cross(edges_a, edges_b), axis=1).sum())


def cluster_mesh(triangles: np.ndarray, target_faces: int) -> tuple[np.ndarray, np.ndarray, float]:
    """Cluster STL triangle vertices and return (vertices, faces, cell_mm)."""
    source_vertices = triangles.reshape(-1, 3)
    lower = source_vertices.min(axis=0)
    span = source_vertices.max(axis=0) - lower
    area = max(triangle_area(triangles), 1.0)

    # A surface made of roughly square cells produces two triangles per cell.
    # The small clamp prevents tiny CAD details from turning into another
    # million-polygon visual while keeping the chassis silhouette crisp.
    cell = max(0.35, float(np.sqrt(area / (2.0 * max(target_faces, 1)))))
    cell = min(cell, float(span.max()) / 12.0)

    clustered_vertices = None
    faces = None
    for _ in range(5):
        keys = np.floor((source_vertices - lower) / cell).astype(np.int64)
        unique_keys, inverse = np.unique(keys, axis=0, return_inverse=True)
        sums = np.zeros((len(unique_keys), 3), dtype=np.float64)
        np.add.at(sums, inverse, source_vertices)
        counts = np.bincount(inverse).astype(np.float64)
        clustered_vertices = sums / counts[:, None]

        candidate_faces = inverse.reshape(-1, 3)
        valid = (
            (candidate_faces[:, 0] != candidate_faces[:, 1])
            & (candidate_faces[:, 0] != candidate_faces[:, 2])
            & (candidate_faces[:, 1] != candidate_faces[:, 2])
        )
        candidate_faces = candidate_faces[valid]
        if len(candidate_faces):
            # Remove duplicate coplanar fragments generated by the cluster
            # operation without changing the winding of the first occurrence.
            canonical = np.sort(candidate_faces, axis=1)
            _, first = np.unique(canonical, axis=0, return_index=True)
            faces = candidate_faces[np.sort(first)]
        else:
            faces = np.empty((0, 3), dtype=np.int64)

        if len(faces) > target_faces * 1.25:
            cell *= 1.35
        elif len(faces) < target_faces * 0.55:
            cell /= 1.22
        else:
            break

    assert clustered_vertices is not None
    assert faces is not None
    return clustered_vertices, faces, cell


def write_obj(path: Path, vertices_mm: np.ndarray, faces: np.ndarray, source: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    # OBJ is written in metres.  This avoids another unit conversion in every
    # visual declaration and makes the generated asset self-describing.
    vertices_m = vertices_mm / 1000.0
    with path.open("w", encoding="utf-8") as stream:
        stream.write(f"# Optimized visual mesh generated from {source.as_posix()}\n")
        stream.write("# Coordinates are metres; source CAD STL is retained unchanged.\n")
        stream.write("o agv_visual\n")
        for x, y, z in vertices_m:
            stream.write(f"v {x:.9g} {y:.9g} {z:.9g}\n")
        for a, b, c in faces:
            stream.write(f"f {a + 1} {b + 1} {c + 1}\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--target-faces", type=int, default=60000)
    args = parser.parse_args()
    triangles = read_binary_stl(args.source)
    vertices, faces, cell = cluster_mesh(triangles, args.target_faces)
    write_obj(args.output, vertices, faces, args.source)
    print(
        f"{args.source}: {len(triangles):,} STL triangles -> "
        f"{len(faces):,} OBJ triangles, {len(vertices):,} vertices, "
        f"cell={cell:.3f} mm, output={args.output}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
