# Generated by Django 5.2.17 on 2026-09-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twin', '0006_shelf_inventory_items'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventlog',
            new_name='twin_eventl_run_id_d614e1_idx',
            old_name='twin_eventl_run_id_7dce70_idx',
        ),
        migrations.RenameIndex(
            model_name='resourcereservation',
            new_name='twin_resour_resourc_92b5fd_idx',
            old_name='twin_resour_resourc_79e93a_idx',
        ),
        migrations.RenameIndex(
            model_name='robotschedule',
            new_name='twin_robots_warehou_4eba13_idx',
            old_name='twin_robots_warehou_c3d031_idx',
        ),
        migrations.RenameIndex(
            model_name='robotschedule',
            new_name='twin_robots_robot_i_6aaaca_idx',
            old_name='twin_robots_robot_i_0c0ee2_idx',
        ),
        migrations.RenameIndex(
            model_name='shelfinventoryitem',
            new_name='twin_shelfi_warehou_984c51_idx',
            old_name='twin_shelfi_warehou_97101e_idx',
        ),
        migrations.RenameIndex(
            model_name='shelfinventoryitem',
            new_name='twin_shelfi_warehou_6b262a_idx',
            old_name='twin_shelfi_warehou_022fde_idx',
        ),
        migrations.RenameIndex(
            model_name='warehouseorder',
            new_name='twin_wareho_warehou_941939_idx',
            old_name='twin_wareho_warehou_9ba0f8_idx',
        ),
        migrations.RenameIndex(
            model_name='workpoint',
            new_name='twin_workpo_warehou_5cb400_idx',
            old_name='twin_workpo_warehou_69518d_idx',
        ),
    ]
