# Generated by Django 5.2.17 on 2026-09-17 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twin', '0008_alter_schedulestop_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('yaw', models.FloatField(default=0.0)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_tags', to='twin.warehouse')),
            ],
            options={
                'ordering': ['warehouse_id', 'tag_id'],
            },
        ),
        migrations.CreateModel(
            name='NavigationTagEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(blank=True, null=True)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('bidirectional', models.BooleanField(default=False)),
                ('from_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='twin.navigationtag')),
                ('to_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='twin.navigationtag')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_edges', to='twin.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='RobotNavigationMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.CharField(db_index=True, max_length=64)),
                ('current_tag_id', models.IntegerField(blank=True, null=True)),
                ('next_tag_id', models.IntegerField(blank=True, null=True)),
                ('route', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PLANNING', 'PLANNING'), ('NAVIGATING', 'NAVIGATING'), ('DEAD_RECKONING', 'DEAD_RECKONING'), ('APPROACH_TAG', 'APPROACH_TAG'), ('TAG_CORRECTION', 'TAG_CORRECTION'), ('PAUSED', 'PAUSED'), ('ROUTE_DEVIATION', 'ROUTE_DEVIATION'), ('TAG_ACQUIRE_FAILED', 'TAG_ACQUIRE_FAILED'), ('ARRIVED', 'ARRIVED'), ('CANCELLED', 'CANCELLED'), ('FAILED', 'FAILED'), ('EMERGENCY_STOPPED', 'EMERGENCY_STOPPED')], db_index=True, default='PENDING', max_length=24)),
                ('route_index', models.PositiveIntegerField(default=0)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('failure_reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='twin.navigationtag')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag_missions', to='twin.warehouse')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='navigationtag',
            constraint=models.UniqueConstraint(fields=('warehouse', 'tag_id'), name='uniq_navigation_tag_per_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='navigationtagedge',
            constraint=models.UniqueConstraint(fields=('warehouse', 'from_tag', 'to_tag'), name='uniq_navigation_edge'),
        ),
        migrations.AddIndex(
            model_name='robotnavigationmission',
            index=models.Index(fields=['warehouse', 'robot_id', 'status'], name='twin_robotn_warehou_816a67_idx'),
        ),
    ]
