# Generated by Django 5.2.17 on 2026-09-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twin', '0010_navigationtag_landmark_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotVda5050Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('mqtt_host', models.CharField(blank=True, max_length=255)),
                ('mqtt_port', models.PositiveIntegerField(default=1883)),
                ('mqtt_username', models.CharField(blank=True, max_length=128)),
                ('mqtt_password_ciphertext', models.TextField(blank=True)),
                ('tls_enabled', models.BooleanField(default=False)),
                ('topic_prefix', models.CharField(default='vda5050', max_length=128)),
                ('interface_name', models.CharField(default='uagv', max_length=64)),
                ('manufacturer', models.CharField(default='PTAGV', max_length=64)),
                ('serial_number', models.CharField(blank=True, max_length=64)),
                ('protocol_version', models.CharField(default='2.0.0', max_length=16)),
                ('mqtt_protocol_version', models.CharField(default='3.1.1', max_length=8)),
                ('allow_task', models.BooleanField(default=True)),
                ('allow_instant_actions', models.BooleanField(default=True)),
                ('auto_reconnect', models.BooleanField(default=True)),
                ('reconnect_interval', models.PositiveIntegerField(default=5)),
                ('connection_timeout', models.PositiveIntegerField(default=5)),
                ('keepalive', models.PositiveIntegerField(default=30)),
                ('client_id', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
